spring.application.name=mcpclient

logging.level.org.springframework.ai.chat.client.advisor=DEBUG
spring.ai.openai.api-key= "API_KEY"
spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers.json

spring.ai.mcp.client.streamable-http.connections.ticketServer.url=http://localhost:8090
spring.ai.mcp.client.streamable-http.connections.ticketServer.endpoint=/mcp